server:
   port: 8765


spring:
   application:
      name: gateway
   cloud:
      config:
         import: optional:configserver:http://localhost:8888/       
         
         server:
           git:
             uri: file://C:/Users/mmduk/eclipse-workspace/git-config-local-repo
       
         enabled: false
       
         import-check:
           enabled: false   
   
   sleuth:
      sampler:
        probability: 1.0
   
   profiles:
      active: native        


#discovery

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    region-default: true





#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
